package com.example.common.message;

public enum EventType {
    USER_REGISTERED, USER_LOGGED_IN, USER_LOGOUT, USER_DELETED,
    USER_UPDATED, USER_TO_ADMIN,

    CARD_CREATED, CARD_BY_ID, CARD_DELETED, CARD_BLOCKED, CARD_ACTIVATED,
    CARD_BALANCE, CARDS_WAITING_BLOCK, CARDS_ALL, CARDS_ALL_BY_USER, CARDS_BY_PARAMETERS,

    TRANSFER
}
