server:
  port: 8082

app:
  kafka:
    topic:
      user-notification: user.notification
      admin-notification: admin.notification

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.common.dto"
        spring.json.type.mapping: notificationDto:com.example.common.dto.NotificationDto